#!/usr/bin/env bash
# Per-project configuration for ios-build-verify (Conjugar).
# Generated by setup_project.sh; safe to hand-edit.
APP_NAME=Conjugar
BUNDLE_ID=biz.joshadams.Conjugar
PROJECT=Conjugar.xcodeproj
SCHEME=Conjugar
TARGET_SIM='iPhone 17'
FIRST_SCREEN_ID=browse_verb_count
MAIN_TABS=(browse models quiz info settings)
MAIN_TABS_COORDS=("63,822" "131,822" "200,822" "269,822" "337,822")
WAIT_FOR_RENDER_BUDGET_S=10
MAIN_TABS_COUNT_ACK=""
ONBOARDING_DISMISS_LABEL=''
