//
//  VerbMap2Tests.swift
//  ConjugarTests
//
//  Created by Joshua Adams on 6/13/26.
//  Copyright © 2026 Josh Adams. All rights reserved.
//

import Testing
@testable import Conjugar

// Phase 6 (B/B2) — the verb→model map + glosses. These tests exercise the shipped
// bundle resource `verbModelMap.xml` (generated by `docs/_build_verbmap.py`) through
// `VerbMap2`, and the data path verb → class number → `ModelCatalog2` model →
// conjugate. (The no-`model:` *resolver* itself is Phase 6 C; here we drive the
// equivalent path with an explicit catalog model, which fully validates the data.)
@Suite("VerbMap2 (Phase 6 — verb→model map + glosses)")
struct VerbMap2Tests {
  static let map = VerbMap2.shared

  /// verb → (default) class number → catalog model → conjugate. The data path.
  static func form(_ infinitive: String, _ tense: Tense2) -> String? {
    guard
      let entry = map.entry(for: infinitive),
      let model = ModelCatalog2.model(forClass: entry.classNumber)
    else { return nil }
    if case .success(let conjugated) = Conjugator2.conjugate(infinitive: infinitive, tense: tense, model: model) {
      return conjugated
    }
    return nil
  }

  // MARK: - Map loads (gate: crux 7)

  // 4,818 <verb> elements collapse to 4,814 distinct infinitives (the 4 homonyms
  // contribute 2 elements each). A nonzero count proves the resource actually
  // shipped in the (test-hosted app) bundle.
  @Test("map loads from the bundle: 4,814 distinct infinitives")
  func mapLoads() {
    #expect(Self.map.count == 4814, "loaded \(Self.map.count) entries (resource bundled?)")
  }

  // MARK: - Marker stripping (crux 3): keys are bare infinitives

  @Test("verb-cell markers are stripped from the key", arguments: [
    "aborregar",  // was aborregar(se)
    "acaecer",    // was acaecer (DEF)
    "apostar",    // was apostar (1)/(2)
  ])
  func bareKeys(infinitive: String) {
    #expect(Self.map.entry(for: infinitive) != nil, "missing bare key \(infinitive)")
  }

  @Test("the marker forms are NOT keys", arguments: ["aborregar(se)", "acaecer (DEF)", "apostar (1)"])
  func noMarkerKeys(raw: String) {
    #expect(Self.map.entry(for: raw) == nil, "marker leaked into key: \(raw)")
  }

  // MARK: - Glosses present (gate, B2; crux 8)

  @Test("no verb is glossless")
  func noGlossless() {
    let glossless = Self.map.entries.values.filter { entry in
      entry.glosses.contains { $0.isEmpty }
    }
    #expect(glossless.isEmpty, "glossless: \(glossless.prefix(8).map(\.infinitive))")
  }

  @Test("glosses are reused verbatim from the oracle / old verbs.xml", arguments: [
    ("abrir", "open"), ("decir", "say"), ("tener", "have"),
    ("caber", "fit"), ("salir", "exit"), ("hacer", "do"),
  ])
  func reusedGlosses(infinitive: String, gloss: String) {
    #expect(Self.map.entry(for: infinitive)?.gloss == gloss)
  }

  // MARK: - Catalog completeness, table-derived from the map (gate; crux 2)

  // The map uses exactly the 106 distinct class numbers of Annex B, and every one
  // resolves to a catalog model — derived from the shipped resource, not a literal.
  @Test("the map uses exactly 106 distinct class numbers")
  func distinctClassCount() {
    let used = Set(Self.map.entries.values.flatMap(\.classNumbers))
    #expect(used.count == 106, "distinct class numbers in map = \(used.count)")
  }

  @Test("every class number used by the map resolves in the catalog")
  func everyMapClassResolves() {
    let used = Set(Self.map.entries.values.flatMap(\.classNumbers))
    let unresolved = used.filter { ModelCatalog2.model(forClass: $0) == nil }.sorted()
    #expect(unresolved.isEmpty, "unresolved class numbers: \(unresolved)")
  }

  // MARK: - Reflexive flag

  @Test("reflexive-only verbs carry rx (and gloss the reflexive sense)", arguments: [
    ("aborregar", "curdle"), ("arrepentir", "repent"), ("atrever", "dare"), ("jactar", "boast"),
  ])
  func reflexiveFlag(infinitive: String, gloss: String) {
    let entry = Self.map.entry(for: infinitive)
    #expect(entry?.isReflexive == true, "\(infinitive) should be reflexive")
    #expect(entry?.gloss == gloss)
  }

  @Test("non-reflexive verbs do not carry rx", arguments: ["abrir", "comer", "hablar", "abrazar"])
  func nonReflexive(infinitive: String) {
    #expect(Self.map.entry(for: infinitive)?.isReflexive == false)
  }

  // MARK: - Homonyms (gate; crux 4) — both senses, default first, distinct glosses

  @Test("homonyms keep both senses in default order with distinct glosses", arguments: [
    ("apostar", ["4B", "1"], ["bet", "station"]),
    ("asolar",  ["4B", "1"], ["raze", "scorch"]),
    ("aterrar", ["1", "4A"], ["terrify", "demolish"]),
    ("atestar", ["4A", "1"], ["stuff", "attest"]),
  ])
  func homonyms(infinitive: String, classes: [String], glosses: [String]) {
    let entry = Self.map.entry(for: infinitive)
    #expect(entry?.isHomonym == true)
    #expect(entry?.classNumbers == classes)
    #expect(entry?.glosses == glosses)
  }

  // The two senses conjugate on their two different models. aterrar's default is the
  // regular "terrify" sense (1 → aterro); its alternate is the diphthong "demolish"
  // sense (4A → atierro).
  @Test("homonym default vs. alternate sense conjugate on their own models")
  func homonymConjugation() {
    #expect(Self.form("aterrar", .presenteDeIndicativo(.firstSingular)) == "aterro")
    guard
      let entry = Self.map.entry(for: "aterrar"),
      let alternate = ModelCatalog2.model(forClass: entry.classNumbers[1]),
      case .success(let form) = Conjugator2.conjugate(infinitive: "aterrar", tense: .presenteDeIndicativo(.firstSingular), model: alternate)
    else { Issue.record("aterrar alternate sense failed to resolve/conjugate"); return }
    #expect(form == "atierro")
  }

  // MARK: - Per-class sample (gate; crux 5/6) — representative verbs via the map

  // One representative verb per class (a spread across the orthographic, stem-vowel,
  // and fundamentally-irregular families), conjugated through the map at the slot
  // that carries that class's irregularity, checked against the oracle.
  static let perClassSample: [(String, Tense2, String)] = [
    // regular + orthographic
    ("abajar", .presenteDeIndicativo(.firstSingular), "abajo"),
    ("abanicar", .pretérito(.firstSingular), "abaniqué"),
    ("abogar", .pretérito(.firstSingular), "abogué"),
    ("averiguar", .pretérito(.firstSingular), "averigüé"),
    ("abrazar", .pretérito(.firstSingular), "abracé"),
    ("vencer", .presenteDeIndicativo(.firstSingular), "venzo"),
    ("coger", .presenteDeIndicativo(.firstSingular), "cojo"),
    ("leer", .pretérito(.thirdSingular), "leyó"),
    ("zurcir", .presenteDeIndicativo(.firstSingular), "zurzo"),
    ("dirigir", .presenteDeIndicativo(.firstSingular), "dirijo"),
    ("distinguir", .presenteDeIndicativo(.firstSingular), "distingo"),
    // stem-vowel (diphthong + raise)
    ("acertar", .presenteDeIndicativo(.firstSingular), "acierto"),     // 4A
    ("acordar", .presenteDeIndicativo(.firstSingular), "acuerdo"),     // 4B
    ("trocar", .presenteDeIndicativo(.firstSingular), "trueco"),       // 4B-1
    ("desosar", .presenteDeIndicativo(.firstSingular), "deshueso"),    // 4B-5
    ("avergonzar", .presenteDeIndicativo(.firstSingular), "avergüenzo"), // 4B-6
    ("atender", .presenteDeIndicativo(.firstSingular), "atiendo"),     // 5A
    ("morder", .presenteDeIndicativo(.firstSingular), "muerdo"),       // 5B
    ("mentir", .presenteDeIndicativo(.firstSingular), "miento"),       // 6A
    ("erguir", .presenteDeIndicativo(.firstSingular), "yergo"),        // 6A-1
    ("medir", .presenteDeIndicativo(.firstSingular), "mido"),          // 6B
    ("elegir", .presenteDeIndicativo(.firstSingular), "elijo"),        // 6B-1
    ("seguir", .presenteDeIndicativo(.firstSingular), "sigo"),         // 6B-2
    ("ceñir", .pretérito(.thirdSingular), "ciñó"),                     // 6B-3
    ("reír", .presenteDeIndicativo(.firstSingular), "río"),            // 6B-4 (base verb; compounds deferred — see docs/phase6_known_issues.md)
    ("dormir", .presenteDeIndicativo(.firstSingular), "duermo"),       // 6C
    ("discernir", .presenteDeIndicativo(.firstSingular), "discierno"), // 15
    ("jugar", .presenteDeIndicativo(.firstSingular), "juego"),         // 16
    ("adquirir", .presenteDeIndicativo(.firstSingular), "adquiero"),   // 17
    // fundamentally irregular
    ("conocer", .presenteDeIndicativo(.firstSingular), "conozco"),     // 7A
    ("lucir", .presenteDeIndicativo(.firstSingular), "luzco"),         // 7B
    ("construir", .presenteDeIndicativo(.firstSingular), "construyo"), // 8
    ("caer", .presenteDeIndicativo(.firstSingular), "caigo"),          // 9
    ("oír", .presenteDeIndicativo(.firstSingular), "oigo"),            // 10
    ("oír", .pretérito(.thirdSingular), "oyó"),
    ("oír", .participioPasado, "oído"),
    ("salir", .presenteDeIndicativo(.firstSingular), "salgo"),         // 11
    ("valer", .presenteDeIndicativo(.firstSingular), "valgo"),         // 12
    ("asir", .presenteDeIndicativo(.firstSingular), "asgo"),           // 13
    ("ver", .presenteDeIndicativo(.firstSingular), "veo"),             // 14
    ("ver", .participioPasado, "visto"),
    ("argüir", .presenteDeIndicativo(.firstSingular), "arguyo"),       // 18
    ("ser", .presenteDeIndicativo(.firstSingular), "soy"),             // 19
    ("estar", .presenteDeIndicativo(.firstSingular), "estoy"),         // 20
    ("haber", .presenteDeIndicativo(.firstSingular), "he"),            // 21
    ("saber", .presenteDeIndicativo(.firstSingular), "sé"),            // 22
    ("caber", .presenteDeIndicativo(.firstSingular), "quepo"),         // 23
    ("ir", .presenteDeIndicativo(.firstSingular), "voy"),              // 24
    ("dar", .presenteDeIndicativo(.firstSingular), "doy"),             // 25
    ("poder", .presenteDeIndicativo(.firstSingular), "puedo"),         // 26
    ("querer", .presenteDeIndicativo(.firstSingular), "quiero"),       // 27
    ("decir", .presenteDeIndicativo(.firstSingular), "digo"),          // 28
    ("decir", .participioPasado, "dicho"),
    ("hacer", .presenteDeIndicativo(.firstSingular), "hago"),          // 29
    ("hacer", .pretérito(.thirdSingular), "hizo"),
    ("poner", .presenteDeIndicativo(.firstSingular), "pongo"),         // 30
    ("poner", .participioPasado, "puesto"),
    ("tener", .presenteDeIndicativo(.firstSingular), "tengo"),         // 31
    ("tener", .pretérito(.firstSingular), "tuve"),
    ("tener", .futuro(.firstSingular), "tendré"),
    ("venir", .presenteDeIndicativo(.firstSingular), "vengo"),         // 32
    ("traer", .presenteDeIndicativo(.firstSingular), "traigo"),        // 33
    ("traer", .pretérito(.firstSingular), "traje"),
    ("conducir", .presenteDeIndicativo(.firstSingular), "conduzco"),   // 34
    ("conducir", .pretérito(.firstSingular), "conduje"),
    ("andar", .pretérito(.firstSingular), "anduve"),                   // 35
  ]

  @Test("per-class sample conjugates correctly via the map", arguments: perClassSample)
  func perClass(infinitive: String, tense: Tense2, expected: String) {
    #expect(Self.form(infinitive, tense) == expected, "\(infinitive) \(tense)")
  }

  // MARK: - Prefix payoff (gate; crux 1) — compounds ride their own stem

  // Each compound maps to its base verb's class; the engine conjugates the compound's
  // OWN stem and the end-anchored features ride along. (reír/sonreír is a known
  // engine gap, tracked in docs/phase6_known_issues.md — not asserted here.)
  static let prefixSample: [(String, Tense2, String)] = [
    ("detener", .presenteDeIndicativo(.firstSingular), "detengo"),
    ("detener", .pretérito(.firstSingular), "detuve"),
    ("detener", .imperativoAfirmativo(.secondSingular), "detén"),
    ("contener", .presenteDeIndicativo(.firstSingular), "contengo"),
    ("obtener", .presenteDeIndicativo(.firstSingular), "obtengo"),
    ("reconocer", .presenteDeIndicativo(.firstSingular), "reconozco"),
    ("descomponer", .presenteDeIndicativo(.firstSingular), "descompongo"),
    ("descomponer", .participioPasado, "descompuesto"),
    ("desdecir", .presenteDeIndicativo(.firstSingular), "desdigo"),
    ("prever", .presenteDeIndicativo(.firstSingular), "preveo"),
    ("prever", .participioPasado, "previsto"),
    ("convenir", .presenteDeIndicativo(.firstSingular), "convengo"),
    ("rehacer", .pretérito(.thirdSingular), "rehízo"),
  ]

  @Test("prefix payoff: compounds conjugate on their own stem", arguments: prefixSample)
  func prefixPayoff(infinitive: String, tense: Tense2, expected: String) {
    #expect(Self.form(infinitive, tense) == expected, "\(infinitive) \(tense)")
  }

  // MARK: - Structural: every class is reachable and errors out on none

  // For each of the 106 class numbers, a representative verb from the map conjugates
  // (present 1s) without erroring — so no class is unreachable or crashes the path.
  // Class 3-14 (abolir) is **defective**: it intentionally suppresses present-1s and
  // returns `.failure` there, so it's exempt from the no-error check (correctness of
  // each class's paradigm is covered by Conjugator2Tests; here we only assert
  // reachability across all 106).
  static let defectiveClasses: Set<String> = ["3-14"]   // abolir — present 1s suppressed by design

  @Test("every class has a representative verb that conjugates without error")
  func everyClassReachable() {
    var representative: [String: String] = [:]
    for entry in Self.map.entries.values {
      representative[entry.classNumber] = entry.infinitive
    }
    var broken: [String] = []
    for (classNumber, infinitive) in representative {
      guard let model = ModelCatalog2.model(forClass: classNumber) else { broken.append(classNumber); continue }
      if Self.defectiveClasses.contains(classNumber) { continue }   // intentional .noForm
      if case .failure = Conjugator2.conjugate(infinitive: infinitive, tense: .presenteDeIndicativo(.firstSingular), model: model) {
        broken.append("\(classNumber):\(infinitive)")
      }
    }
    #expect(broken.isEmpty, "classes with no working representative: \(broken.sorted())")
    #expect(representative.count == 106, "representatives cover \(representative.count) classes")
  }
}
